repo_url: https://breezy-weather.github.io/fdroid-repo/fdroid/repo
repo_name: Breezy Weather
repo_description: >-
   The F-Droid repository for Breezy Weather

repo_keyalias: KEYALIAS

keystore: keystore.keystore

keystorepass: "KEYSTORE_PASS"

keypass: "KEY_PASS"

keydname: KEYDNAME