name: Build

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/github.yml'
      - 'build.sh'
      - 'update.sh'
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          apt update
          apt install aapt curl git fdroidserver -y
          sed -i "s/KEYALIAS/$(echo "$KEYALIAS" | sed -e "s/\&/\\\&/")/" config.yml
          sed -i "s/KEYSTORE_PASS/$(echo "$KEYSTORE_PASS" | sed -e "s/\&/\\\&/")/" config.yml
          sed -i "s/KEY_PASS/$(echo "$KEY_PASS" | sed -e "s/\&/\\\&/")/" config.yml
          sed -i "s/KEYDNAME/$(echo "$KEYDNAME" | sed -e "s/\&/\\\&/")/" config.yml
          chmod +x update.sh

          mkdir -p fdroid/repo
          echo "$KEYSTORE" | base64 -d - > fdroid/keystore.keystore
          cp config.yml fdroid/
          ./update.sh standard
          rm fdroid/keystore.keystore
          rm fdroid/config.yml
          mkdir public
          mv fdroid public/

          mkdir -p fdroid/repo
          echo "$KEYSTORE" | base64 -d - > fdroid/keystore.keystore
          cp config.yml fdroid/
          sed -i 's/fdroid-repo\/gplay/fdroid-repo\/fdroid-version\/gplay/g' fdroid/config.yml
          sed -i 's/Breezy Weather/Breezy Weather (Google Play, deprecated, please migrate to the standard repo)/' fdroid/config.yml
          ./update.sh standard
          rm fdroid/keystore.keystore
          rm fdroid/config.yml
          mkdir public/gplay-version/
          mv fdroid public/gplay-version/

          mkdir -p fdroid/repo
          echo "$KEYSTORE" | base64 -d - > fdroid/keystore.keystore
          cp config.yml fdroid/
          sed -i 's/fdroid-repo\/fdroid/fdroid-repo\/fdroid-version\/fdroid/g' fdroid/config.yml
          sed -i 's/Breezy Weather/Breezy Weather (Free network sources-only)/' fdroid/config.yml
          ./update.sh freenet
          rm fdroid/keystore.keystore
          rm fdroid/config.yml
          mkdir public/fdroid-version/
          mv fdroid public/fdroid-version/
        env:
          KEYSTORE: ${{ secrets.KEYSTORE_FDROID }}
          KEYALIAS: ${{ secrets.ALIAS_FDROID }}
          KEYSTORE_PASS: ${{ secrets.KEY_STORE_PASSWORD_FDROID }}
          KEY_PASS: ${{ secrets.KEY_PASSWORD_FDROID }}
          KEYDNAME: ${{ secrets.KEYDNAME_FDROID }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
